project_id = "nvnvyzxzjezlgzgpniyt"

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.evaluate-submission]
verify_jwt = false

[functions.generate-project-brief]
verify_jwt = true

[functions.founder-agent]
verify_jwt = true






